/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RecompensasRouteImport } from './routes/recompensas'
import { Route as MotoboyRouteImport } from './routes/motoboy'
import { Route as FinalizarRouteImport } from './routes/finalizar'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as BaixarAppRouteImport } from './routes/baixar-app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RastrearTokenRouteImport } from './routes/rastrear.$token'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as CTokenRouteImport } from './routes/c.$token'
import { Route as ApiCopilotChatRouteImport } from './routes/api/copilot-chat'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedSlaRouteImport } from './routes/_authenticated/sla'
import { Route as AuthenticatedRushRouteImport } from './routes/_authenticated/rush'
import { Route as AuthenticatedRotasRouteImport } from './routes/_authenticated/rotas'
import { Route as AuthenticatedProvaEntregaRouteImport } from './routes/_authenticated/prova-entrega'
import { Route as AuthenticatedPrevisaoRouteImport } from './routes/_authenticated/previsao'
import { Route as AuthenticatedPrecificacaoRouteImport } from './routes/_authenticated/precificacao'
import { Route as AuthenticatedPrePreparoRouteImport } from './routes/_authenticated/pre-preparo'
import { Route as AuthenticatedPdvRouteImport } from './routes/_authenticated/pdv'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedModelosRouteImport } from './routes/_authenticated/modelos'
import { Route as AuthenticatedMesasRouteImport } from './routes/_authenticated/mesas'
import { Route as AuthenticatedLucratividadeRouteImport } from './routes/_authenticated/lucratividade'
import { Route as AuthenticatedIndiqueRouteImport } from './routes/_authenticated/indique'
import { Route as AuthenticatedIndicacoesRouteImport } from './routes/_authenticated/indicacoes'
import { Route as AuthenticatedImpressaoRouteImport } from './routes/_authenticated/impressao'
import { Route as AuthenticatedImportarRouteImport } from './routes/_authenticated/importar'
import { Route as AuthenticatedGarconsRouteImport } from './routes/_authenticated/garcons'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedFichaTecnicaRouteImport } from './routes/_authenticated/ficha-tecnica'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedEntregasRouteImport } from './routes/_authenticated/entregas'
import { Route as AuthenticatedCopilotoRouteImport } from './routes/_authenticated/copiloto'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedCarrinhosRouteImport } from './routes/_authenticated/carrinhos'
import { Route as AuthenticatedCaixaRouteImport } from './routes/_authenticated/caixa'
import { Route as AuthenticatedBibliotecaRouteImport } from './routes/_authenticated/biblioteca'
import { Route as AuthenticatedAvaliacoesRouteImport } from './routes/_authenticated/avaliacoes'
import { Route as AuthenticatedAutomacoesRouteImport } from './routes/_authenticated/automacoes'
import { Route as AuthenticatedAniversariantesRouteImport } from './routes/_authenticated/aniversariantes'
import { Route as AuthenticatedAlertasSonorosRouteImport } from './routes/_authenticated/alertas-sonoros'
import { Route as AuthenticatedAiGrowthRouteImport } from './routes/_authenticated/ai-growth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp-webhook'
import { Route as AuthenticatedRastrearOrderIdRouteImport } from './routes/_authenticated/rastrear.$orderId'
import { Route as AuthenticatedAvaliarOrderIdRouteImport } from './routes/_authenticated/avaliar.$orderId'
import { Route as ApiPublicWhatsappWebhookEventRouteImport } from './routes/api/public/whatsapp-webhook.$event'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RecompensasRoute = RecompensasRouteImport.update({
  id: '/recompensas',
  path: '/recompensas',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoboyRoute = MotoboyRouteImport.update({
  id: '/motoboy',
  path: '/motoboy',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalizarRoute = FinalizarRouteImport.update({
  id: '/finalizar',
  path: '/finalizar',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const BaixarAppRoute = BaixarAppRouteImport.update({
  id: '/baixar-app',
  path: '/baixar-app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RastrearTokenRoute = RastrearTokenRouteImport.update({
  id: '/rastrear/$token',
  path: '/rastrear/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotChatRoute = ApiCopilotChatRouteImport.update({
  id: '/api/copilot-chat',
  path: '/api/copilot-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSlaRoute = AuthenticatedSlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRushRoute = AuthenticatedRushRouteImport.update({
  id: '/rush',
  path: '/rush',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRotasRoute = AuthenticatedRotasRouteImport.update({
  id: '/rotas',
  path: '/rotas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProvaEntregaRoute =
  AuthenticatedProvaEntregaRouteImport.update({
    id: '/prova-entrega',
    path: '/prova-entrega',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrevisaoRoute = AuthenticatedPrevisaoRouteImport.update({
  id: '/previsao',
  path: '/previsao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrecificacaoRoute =
  AuthenticatedPrecificacaoRouteImport.update({
    id: '/precificacao',
    path: '/precificacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrePreparoRoute = AuthenticatedPrePreparoRouteImport.update({
  id: '/pre-preparo',
  path: '/pre-preparo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPdvRoute = AuthenticatedPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModelosRoute = AuthenticatedModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMesasRoute = AuthenticatedMesasRouteImport.update({
  id: '/mesas',
  path: '/mesas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLucratividadeRoute =
  AuthenticatedLucratividadeRouteImport.update({
    id: '/lucratividade',
    path: '/lucratividade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndiqueRoute = AuthenticatedIndiqueRouteImport.update({
  id: '/indique',
  path: '/indique',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIndicacoesRoute = AuthenticatedIndicacoesRouteImport.update({
  id: '/indicacoes',
  path: '/indicacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImpressaoRoute = AuthenticatedImpressaoRouteImport.update({
  id: '/impressao',
  path: '/impressao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportarRoute = AuthenticatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGarconsRoute = AuthenticatedGarconsRouteImport.update({
  id: '/garcons',
  path: '/garcons',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFichaTecnicaRoute =
  AuthenticatedFichaTecnicaRouteImport.update({
    id: '/ficha-tecnica',
    path: '/ficha-tecnica',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntregasRoute = AuthenticatedEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCopilotoRoute = AuthenticatedCopilotoRouteImport.update({
  id: '/copiloto',
  path: '/copiloto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarrinhosRoute = AuthenticatedCarrinhosRouteImport.update({
  id: '/carrinhos',
  path: '/carrinhos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCaixaRoute = AuthenticatedCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBibliotecaRoute = AuthenticatedBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAvaliacoesRoute = AuthenticatedAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomacoesRoute = AuthenticatedAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAniversariantesRoute =
  AuthenticatedAniversariantesRouteImport.update({
    id: '/aniversariantes',
    path: '/aniversariantes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlertasSonorosRoute =
  AuthenticatedAlertasSonorosRouteImport.update({
    id: '/alertas-sonoros',
    path: '/alertas-sonoros',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiGrowthRoute = AuthenticatedAiGrowthRouteImport.update({
  id: '/ai-growth',
  path: '/ai-growth',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp-webhook',
    path: '/api/public/whatsapp-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRastrearOrderIdRoute =
  AuthenticatedRastrearOrderIdRouteImport.update({
    id: '/rastrear/$orderId',
    path: '/rastrear/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAvaliarOrderIdRoute =
  AuthenticatedAvaliarOrderIdRouteImport.update({
    id: '/avaliar/$orderId',
    path: '/avaliar/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWhatsappWebhookEventRoute =
  ApiPublicWhatsappWebhookEventRouteImport.update({
    id: '/$event',
    path: '/$event',
    getParentRoute: () => ApiPublicWhatsappWebhookRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/baixar-app': typeof BaixarAppRoute
  '/carrinho': typeof CarrinhoRoute
  '/finalizar': typeof FinalizarRoute
  '/motoboy': typeof MotoboyRoute
  '/recompensas': typeof RecompensasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai-growth': typeof AuthenticatedAiGrowthRoute
  '/alertas-sonoros': typeof AuthenticatedAlertasSonorosRoute
  '/aniversariantes': typeof AuthenticatedAniversariantesRoute
  '/automacoes': typeof AuthenticatedAutomacoesRoute
  '/avaliacoes': typeof AuthenticatedAvaliacoesRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/carrinhos': typeof AuthenticatedCarrinhosRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/conta': typeof AuthenticatedContaRoute
  '/copiloto': typeof AuthenticatedCopilotoRoute
  '/entregas': typeof AuthenticatedEntregasRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/ficha-tecnica': typeof AuthenticatedFichaTecnicaRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/garcons': typeof AuthenticatedGarconsRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/impressao': typeof AuthenticatedImpressaoRoute
  '/indicacoes': typeof AuthenticatedIndicacoesRoute
  '/indique': typeof AuthenticatedIndiqueRoute
  '/lucratividade': typeof AuthenticatedLucratividadeRoute
  '/mesas': typeof AuthenticatedMesasRoute
  '/modelos': typeof AuthenticatedModelosRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pdv': typeof AuthenticatedPdvRoute
  '/pre-preparo': typeof AuthenticatedPrePreparoRoute
  '/precificacao': typeof AuthenticatedPrecificacaoRoute
  '/previsao': typeof AuthenticatedPrevisaoRoute
  '/prova-entrega': typeof AuthenticatedProvaEntregaRoute
  '/rotas': typeof AuthenticatedRotasRoute
  '/rush': typeof AuthenticatedRushRoute
  '/sla': typeof AuthenticatedSlaRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/api/copilot-chat': typeof ApiCopilotChatRoute
  '/c/$token': typeof CTokenRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/r/$code': typeof RCodeRoute
  '/rastrear/$token': typeof RastrearTokenRoute
  '/avaliar/$orderId': typeof AuthenticatedAvaliarOrderIdRoute
  '/rastrear/$orderId': typeof AuthenticatedRastrearOrderIdRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRouteWithChildren
  '/api/public/whatsapp-webhook/$event': typeof ApiPublicWhatsappWebhookEventRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/baixar-app': typeof BaixarAppRoute
  '/carrinho': typeof CarrinhoRoute
  '/finalizar': typeof FinalizarRoute
  '/motoboy': typeof MotoboyRoute
  '/recompensas': typeof RecompensasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai-growth': typeof AuthenticatedAiGrowthRoute
  '/alertas-sonoros': typeof AuthenticatedAlertasSonorosRoute
  '/aniversariantes': typeof AuthenticatedAniversariantesRoute
  '/automacoes': typeof AuthenticatedAutomacoesRoute
  '/avaliacoes': typeof AuthenticatedAvaliacoesRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/carrinhos': typeof AuthenticatedCarrinhosRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/conta': typeof AuthenticatedContaRoute
  '/copiloto': typeof AuthenticatedCopilotoRoute
  '/entregas': typeof AuthenticatedEntregasRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/ficha-tecnica': typeof AuthenticatedFichaTecnicaRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/garcons': typeof AuthenticatedGarconsRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/impressao': typeof AuthenticatedImpressaoRoute
  '/indicacoes': typeof AuthenticatedIndicacoesRoute
  '/indique': typeof AuthenticatedIndiqueRoute
  '/lucratividade': typeof AuthenticatedLucratividadeRoute
  '/mesas': typeof AuthenticatedMesasRoute
  '/modelos': typeof AuthenticatedModelosRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pdv': typeof AuthenticatedPdvRoute
  '/pre-preparo': typeof AuthenticatedPrePreparoRoute
  '/precificacao': typeof AuthenticatedPrecificacaoRoute
  '/previsao': typeof AuthenticatedPrevisaoRoute
  '/prova-entrega': typeof AuthenticatedProvaEntregaRoute
  '/rotas': typeof AuthenticatedRotasRoute
  '/rush': typeof AuthenticatedRushRoute
  '/sla': typeof AuthenticatedSlaRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/api/copilot-chat': typeof ApiCopilotChatRoute
  '/c/$token': typeof CTokenRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/r/$code': typeof RCodeRoute
  '/rastrear/$token': typeof RastrearTokenRoute
  '/avaliar/$orderId': typeof AuthenticatedAvaliarOrderIdRoute
  '/rastrear/$orderId': typeof AuthenticatedRastrearOrderIdRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRouteWithChildren
  '/api/public/whatsapp-webhook/$event': typeof ApiPublicWhatsappWebhookEventRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/baixar-app': typeof BaixarAppRoute
  '/carrinho': typeof CarrinhoRoute
  '/finalizar': typeof FinalizarRoute
  '/motoboy': typeof MotoboyRoute
  '/recompensas': typeof RecompensasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ai-growth': typeof AuthenticatedAiGrowthRoute
  '/_authenticated/alertas-sonoros': typeof AuthenticatedAlertasSonorosRoute
  '/_authenticated/aniversariantes': typeof AuthenticatedAniversariantesRoute
  '/_authenticated/automacoes': typeof AuthenticatedAutomacoesRoute
  '/_authenticated/avaliacoes': typeof AuthenticatedAvaliacoesRoute
  '/_authenticated/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/_authenticated/caixa': typeof AuthenticatedCaixaRoute
  '/_authenticated/carrinhos': typeof AuthenticatedCarrinhosRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/_authenticated/copiloto': typeof AuthenticatedCopilotoRoute
  '/_authenticated/entregas': typeof AuthenticatedEntregasRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/ficha-tecnica': typeof AuthenticatedFichaTecnicaRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/garcons': typeof AuthenticatedGarconsRoute
  '/_authenticated/importar': typeof AuthenticatedImportarRoute
  '/_authenticated/impressao': typeof AuthenticatedImpressaoRoute
  '/_authenticated/indicacoes': typeof AuthenticatedIndicacoesRoute
  '/_authenticated/indique': typeof AuthenticatedIndiqueRoute
  '/_authenticated/lucratividade': typeof AuthenticatedLucratividadeRoute
  '/_authenticated/mesas': typeof AuthenticatedMesasRoute
  '/_authenticated/modelos': typeof AuthenticatedModelosRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/pdv': typeof AuthenticatedPdvRoute
  '/_authenticated/pre-preparo': typeof AuthenticatedPrePreparoRoute
  '/_authenticated/precificacao': typeof AuthenticatedPrecificacaoRoute
  '/_authenticated/previsao': typeof AuthenticatedPrevisaoRoute
  '/_authenticated/prova-entrega': typeof AuthenticatedProvaEntregaRoute
  '/_authenticated/rotas': typeof AuthenticatedRotasRoute
  '/_authenticated/rush': typeof AuthenticatedRushRoute
  '/_authenticated/sla': typeof AuthenticatedSlaRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/api/copilot-chat': typeof ApiCopilotChatRoute
  '/c/$token': typeof CTokenRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/r/$code': typeof RCodeRoute
  '/rastrear/$token': typeof RastrearTokenRoute
  '/_authenticated/avaliar/$orderId': typeof AuthenticatedAvaliarOrderIdRoute
  '/_authenticated/rastrear/$orderId': typeof AuthenticatedRastrearOrderIdRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRouteWithChildren
  '/api/public/whatsapp-webhook/$event': typeof ApiPublicWhatsappWebhookEventRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/baixar-app'
    | '/carrinho'
    | '/finalizar'
    | '/motoboy'
    | '/recompensas'
    | '/sitemap.xml'
    | '/admin'
    | '/ai-growth'
    | '/alertas-sonoros'
    | '/aniversariantes'
    | '/automacoes'
    | '/avaliacoes'
    | '/biblioteca'
    | '/caixa'
    | '/carrinhos'
    | '/clientes'
    | '/conta'
    | '/copiloto'
    | '/entregas'
    | '/estoque'
    | '/ficha-tecnica'
    | '/financeiro'
    | '/garcons'
    | '/importar'
    | '/impressao'
    | '/indicacoes'
    | '/indique'
    | '/lucratividade'
    | '/mesas'
    | '/modelos'
    | '/notificacoes'
    | '/pdv'
    | '/pre-preparo'
    | '/precificacao'
    | '/previsao'
    | '/prova-entrega'
    | '/rotas'
    | '/rush'
    | '/sla'
    | '/usuarios'
    | '/whatsapp'
    | '/api/copilot-chat'
    | '/c/$token'
    | '/produto/$id'
    | '/r/$code'
    | '/rastrear/$token'
    | '/avaliar/$orderId'
    | '/rastrear/$orderId'
    | '/api/public/whatsapp-webhook'
    | '/api/public/whatsapp-webhook/$event'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/baixar-app'
    | '/carrinho'
    | '/finalizar'
    | '/motoboy'
    | '/recompensas'
    | '/sitemap.xml'
    | '/admin'
    | '/ai-growth'
    | '/alertas-sonoros'
    | '/aniversariantes'
    | '/automacoes'
    | '/avaliacoes'
    | '/biblioteca'
    | '/caixa'
    | '/carrinhos'
    | '/clientes'
    | '/conta'
    | '/copiloto'
    | '/entregas'
    | '/estoque'
    | '/ficha-tecnica'
    | '/financeiro'
    | '/garcons'
    | '/importar'
    | '/impressao'
    | '/indicacoes'
    | '/indique'
    | '/lucratividade'
    | '/mesas'
    | '/modelos'
    | '/notificacoes'
    | '/pdv'
    | '/pre-preparo'
    | '/precificacao'
    | '/previsao'
    | '/prova-entrega'
    | '/rotas'
    | '/rush'
    | '/sla'
    | '/usuarios'
    | '/whatsapp'
    | '/api/copilot-chat'
    | '/c/$token'
    | '/produto/$id'
    | '/r/$code'
    | '/rastrear/$token'
    | '/avaliar/$orderId'
    | '/rastrear/$orderId'
    | '/api/public/whatsapp-webhook'
    | '/api/public/whatsapp-webhook/$event'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/baixar-app'
    | '/carrinho'
    | '/finalizar'
    | '/motoboy'
    | '/recompensas'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/ai-growth'
    | '/_authenticated/alertas-sonoros'
    | '/_authenticated/aniversariantes'
    | '/_authenticated/automacoes'
    | '/_authenticated/avaliacoes'
    | '/_authenticated/biblioteca'
    | '/_authenticated/caixa'
    | '/_authenticated/carrinhos'
    | '/_authenticated/clientes'
    | '/_authenticated/conta'
    | '/_authenticated/copiloto'
    | '/_authenticated/entregas'
    | '/_authenticated/estoque'
    | '/_authenticated/ficha-tecnica'
    | '/_authenticated/financeiro'
    | '/_authenticated/garcons'
    | '/_authenticated/importar'
    | '/_authenticated/impressao'
    | '/_authenticated/indicacoes'
    | '/_authenticated/indique'
    | '/_authenticated/lucratividade'
    | '/_authenticated/mesas'
    | '/_authenticated/modelos'
    | '/_authenticated/notificacoes'
    | '/_authenticated/pdv'
    | '/_authenticated/pre-preparo'
    | '/_authenticated/precificacao'
    | '/_authenticated/previsao'
    | '/_authenticated/prova-entrega'
    | '/_authenticated/rotas'
    | '/_authenticated/rush'
    | '/_authenticated/sla'
    | '/_authenticated/usuarios'
    | '/_authenticated/whatsapp'
    | '/api/copilot-chat'
    | '/c/$token'
    | '/produto/$id'
    | '/r/$code'
    | '/rastrear/$token'
    | '/_authenticated/avaliar/$orderId'
    | '/_authenticated/rastrear/$orderId'
    | '/api/public/whatsapp-webhook'
    | '/api/public/whatsapp-webhook/$event'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BaixarAppRoute: typeof BaixarAppRoute
  CarrinhoRoute: typeof CarrinhoRoute
  FinalizarRoute: typeof FinalizarRoute
  MotoboyRoute: typeof MotoboyRoute
  RecompensasRoute: typeof RecompensasRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiCopilotChatRoute: typeof ApiCopilotChatRoute
  CTokenRoute: typeof CTokenRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
  RCodeRoute: typeof RCodeRoute
  RastrearTokenRoute: typeof RastrearTokenRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recompensas': {
      id: '/recompensas'
      path: '/recompensas'
      fullPath: '/recompensas'
      preLoaderRoute: typeof RecompensasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motoboy': {
      id: '/motoboy'
      path: '/motoboy'
      fullPath: '/motoboy'
      preLoaderRoute: typeof MotoboyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finalizar': {
      id: '/finalizar'
      path: '/finalizar'
      fullPath: '/finalizar'
      preLoaderRoute: typeof FinalizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baixar-app': {
      id: '/baixar-app'
      path: '/baixar-app'
      fullPath: '/baixar-app'
      preLoaderRoute: typeof BaixarAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rastrear/$token': {
      id: '/rastrear/$token'
      path: '/rastrear/$token'
      fullPath: '/rastrear/$token'
      preLoaderRoute: typeof RastrearTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilot-chat': {
      id: '/api/copilot-chat'
      path: '/api/copilot-chat'
      fullPath: '/api/copilot-chat'
      preLoaderRoute: typeof ApiCopilotChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sla': {
      id: '/_authenticated/sla'
      path: '/sla'
      fullPath: '/sla'
      preLoaderRoute: typeof AuthenticatedSlaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rush': {
      id: '/_authenticated/rush'
      path: '/rush'
      fullPath: '/rush'
      preLoaderRoute: typeof AuthenticatedRushRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rotas': {
      id: '/_authenticated/rotas'
      path: '/rotas'
      fullPath: '/rotas'
      preLoaderRoute: typeof AuthenticatedRotasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prova-entrega': {
      id: '/_authenticated/prova-entrega'
      path: '/prova-entrega'
      fullPath: '/prova-entrega'
      preLoaderRoute: typeof AuthenticatedProvaEntregaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/previsao': {
      id: '/_authenticated/previsao'
      path: '/previsao'
      fullPath: '/previsao'
      preLoaderRoute: typeof AuthenticatedPrevisaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/precificacao': {
      id: '/_authenticated/precificacao'
      path: '/precificacao'
      fullPath: '/precificacao'
      preLoaderRoute: typeof AuthenticatedPrecificacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pre-preparo': {
      id: '/_authenticated/pre-preparo'
      path: '/pre-preparo'
      fullPath: '/pre-preparo'
      preLoaderRoute: typeof AuthenticatedPrePreparoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pdv': {
      id: '/_authenticated/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof AuthenticatedPdvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modelos': {
      id: '/_authenticated/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof AuthenticatedModelosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mesas': {
      id: '/_authenticated/mesas'
      path: '/mesas'
      fullPath: '/mesas'
      preLoaderRoute: typeof AuthenticatedMesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lucratividade': {
      id: '/_authenticated/lucratividade'
      path: '/lucratividade'
      fullPath: '/lucratividade'
      preLoaderRoute: typeof AuthenticatedLucratividadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indique': {
      id: '/_authenticated/indique'
      path: '/indique'
      fullPath: '/indique'
      preLoaderRoute: typeof AuthenticatedIndiqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indicacoes': {
      id: '/_authenticated/indicacoes'
      path: '/indicacoes'
      fullPath: '/indicacoes'
      preLoaderRoute: typeof AuthenticatedIndicacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impressao': {
      id: '/_authenticated/impressao'
      path: '/impressao'
      fullPath: '/impressao'
      preLoaderRoute: typeof AuthenticatedImpressaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importar': {
      id: '/_authenticated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AuthenticatedImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/garcons': {
      id: '/_authenticated/garcons'
      path: '/garcons'
      fullPath: '/garcons'
      preLoaderRoute: typeof AuthenticatedGarconsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ficha-tecnica': {
      id: '/_authenticated/ficha-tecnica'
      path: '/ficha-tecnica'
      fullPath: '/ficha-tecnica'
      preLoaderRoute: typeof AuthenticatedFichaTecnicaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entregas': {
      id: '/_authenticated/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof AuthenticatedEntregasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copiloto': {
      id: '/_authenticated/copiloto'
      path: '/copiloto'
      fullPath: '/copiloto'
      preLoaderRoute: typeof AuthenticatedCopilotoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carrinhos': {
      id: '/_authenticated/carrinhos'
      path: '/carrinhos'
      fullPath: '/carrinhos'
      preLoaderRoute: typeof AuthenticatedCarrinhosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caixa': {
      id: '/_authenticated/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof AuthenticatedCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblioteca': {
      id: '/_authenticated/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AuthenticatedBibliotecaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avaliacoes': {
      id: '/_authenticated/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/avaliacoes'
      preLoaderRoute: typeof AuthenticatedAvaliacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automacoes': {
      id: '/_authenticated/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AuthenticatedAutomacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aniversariantes': {
      id: '/_authenticated/aniversariantes'
      path: '/aniversariantes'
      fullPath: '/aniversariantes'
      preLoaderRoute: typeof AuthenticatedAniversariantesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alertas-sonoros': {
      id: '/_authenticated/alertas-sonoros'
      path: '/alertas-sonoros'
      fullPath: '/alertas-sonoros'
      preLoaderRoute: typeof AuthenticatedAlertasSonorosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-growth': {
      id: '/_authenticated/ai-growth'
      path: '/ai-growth'
      fullPath: '/ai-growth'
      preLoaderRoute: typeof AuthenticatedAiGrowthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/whatsapp-webhook': {
      id: '/api/public/whatsapp-webhook'
      path: '/api/public/whatsapp-webhook'
      fullPath: '/api/public/whatsapp-webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rastrear/$orderId': {
      id: '/_authenticated/rastrear/$orderId'
      path: '/rastrear/$orderId'
      fullPath: '/rastrear/$orderId'
      preLoaderRoute: typeof AuthenticatedRastrearOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avaliar/$orderId': {
      id: '/_authenticated/avaliar/$orderId'
      path: '/avaliar/$orderId'
      fullPath: '/avaliar/$orderId'
      preLoaderRoute: typeof AuthenticatedAvaliarOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/whatsapp-webhook/$event': {
      id: '/api/public/whatsapp-webhook/$event'
      path: '/$event'
      fullPath: '/api/public/whatsapp-webhook/$event'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookEventRouteImport
      parentRoute: typeof ApiPublicWhatsappWebhookRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAiGrowthRoute: typeof AuthenticatedAiGrowthRoute
  AuthenticatedAlertasSonorosRoute: typeof AuthenticatedAlertasSonorosRoute
  AuthenticatedAniversariantesRoute: typeof AuthenticatedAniversariantesRoute
  AuthenticatedAutomacoesRoute: typeof AuthenticatedAutomacoesRoute
  AuthenticatedAvaliacoesRoute: typeof AuthenticatedAvaliacoesRoute
  AuthenticatedBibliotecaRoute: typeof AuthenticatedBibliotecaRoute
  AuthenticatedCaixaRoute: typeof AuthenticatedCaixaRoute
  AuthenticatedCarrinhosRoute: typeof AuthenticatedCarrinhosRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedCopilotoRoute: typeof AuthenticatedCopilotoRoute
  AuthenticatedEntregasRoute: typeof AuthenticatedEntregasRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedFichaTecnicaRoute: typeof AuthenticatedFichaTecnicaRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedGarconsRoute: typeof AuthenticatedGarconsRoute
  AuthenticatedImportarRoute: typeof AuthenticatedImportarRoute
  AuthenticatedImpressaoRoute: typeof AuthenticatedImpressaoRoute
  AuthenticatedIndicacoesRoute: typeof AuthenticatedIndicacoesRoute
  AuthenticatedIndiqueRoute: typeof AuthenticatedIndiqueRoute
  AuthenticatedLucratividadeRoute: typeof AuthenticatedLucratividadeRoute
  AuthenticatedMesasRoute: typeof AuthenticatedMesasRoute
  AuthenticatedModelosRoute: typeof AuthenticatedModelosRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPdvRoute: typeof AuthenticatedPdvRoute
  AuthenticatedPrePreparoRoute: typeof AuthenticatedPrePreparoRoute
  AuthenticatedPrecificacaoRoute: typeof AuthenticatedPrecificacaoRoute
  AuthenticatedPrevisaoRoute: typeof AuthenticatedPrevisaoRoute
  AuthenticatedProvaEntregaRoute: typeof AuthenticatedProvaEntregaRoute
  AuthenticatedRotasRoute: typeof AuthenticatedRotasRoute
  AuthenticatedRushRoute: typeof AuthenticatedRushRoute
  AuthenticatedSlaRoute: typeof AuthenticatedSlaRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
  AuthenticatedAvaliarOrderIdRoute: typeof AuthenticatedAvaliarOrderIdRoute
  AuthenticatedRastrearOrderIdRoute: typeof AuthenticatedRastrearOrderIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAiGrowthRoute: AuthenticatedAiGrowthRoute,
  AuthenticatedAlertasSonorosRoute: AuthenticatedAlertasSonorosRoute,
  AuthenticatedAniversariantesRoute: AuthenticatedAniversariantesRoute,
  AuthenticatedAutomacoesRoute: AuthenticatedAutomacoesRoute,
  AuthenticatedAvaliacoesRoute: AuthenticatedAvaliacoesRoute,
  AuthenticatedBibliotecaRoute: AuthenticatedBibliotecaRoute,
  AuthenticatedCaixaRoute: AuthenticatedCaixaRoute,
  AuthenticatedCarrinhosRoute: AuthenticatedCarrinhosRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedCopilotoRoute: AuthenticatedCopilotoRoute,
  AuthenticatedEntregasRoute: AuthenticatedEntregasRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedFichaTecnicaRoute: AuthenticatedFichaTecnicaRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedGarconsRoute: AuthenticatedGarconsRoute,
  AuthenticatedImportarRoute: AuthenticatedImportarRoute,
  AuthenticatedImpressaoRoute: AuthenticatedImpressaoRoute,
  AuthenticatedIndicacoesRoute: AuthenticatedIndicacoesRoute,
  AuthenticatedIndiqueRoute: AuthenticatedIndiqueRoute,
  AuthenticatedLucratividadeRoute: AuthenticatedLucratividadeRoute,
  AuthenticatedMesasRoute: AuthenticatedMesasRoute,
  AuthenticatedModelosRoute: AuthenticatedModelosRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPdvRoute: AuthenticatedPdvRoute,
  AuthenticatedPrePreparoRoute: AuthenticatedPrePreparoRoute,
  AuthenticatedPrecificacaoRoute: AuthenticatedPrecificacaoRoute,
  AuthenticatedPrevisaoRoute: AuthenticatedPrevisaoRoute,
  AuthenticatedProvaEntregaRoute: AuthenticatedProvaEntregaRoute,
  AuthenticatedRotasRoute: AuthenticatedRotasRoute,
  AuthenticatedRushRoute: AuthenticatedRushRoute,
  AuthenticatedSlaRoute: AuthenticatedSlaRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
  AuthenticatedAvaliarOrderIdRoute: AuthenticatedAvaliarOrderIdRoute,
  AuthenticatedRastrearOrderIdRoute: AuthenticatedRastrearOrderIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicWhatsappWebhookRouteChildren {
  ApiPublicWhatsappWebhookEventRoute: typeof ApiPublicWhatsappWebhookEventRoute
}

const ApiPublicWhatsappWebhookRouteChildren: ApiPublicWhatsappWebhookRouteChildren =
  {
    ApiPublicWhatsappWebhookEventRoute: ApiPublicWhatsappWebhookEventRoute,
  }

const ApiPublicWhatsappWebhookRouteWithChildren =
  ApiPublicWhatsappWebhookRoute._addFileChildren(
    ApiPublicWhatsappWebhookRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BaixarAppRoute: BaixarAppRoute,
  CarrinhoRoute: CarrinhoRoute,
  FinalizarRoute: FinalizarRoute,
  MotoboyRoute: MotoboyRoute,
  RecompensasRoute: RecompensasRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiCopilotChatRoute: ApiCopilotChatRoute,
  CTokenRoute: CTokenRoute,
  ProdutoIdRoute: ProdutoIdRoute,
  RCodeRoute: RCodeRoute,
  RastrearTokenRoute: RastrearTokenRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
