/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RecompensasRouteImport } from './routes/recompensas'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as BaixarAppRouteImport } from './routes/baixar-app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as ApiCopilotChatRouteImport } from './routes/api/copilot-chat'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedRushRouteImport } from './routes/_authenticated/rush'
import { Route as AuthenticatedPrevisaoRouteImport } from './routes/_authenticated/previsao'
import { Route as AuthenticatedPrecificacaoRouteImport } from './routes/_authenticated/precificacao'
import { Route as AuthenticatedPdvRouteImport } from './routes/_authenticated/pdv'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedModelosRouteImport } from './routes/_authenticated/modelos'
import { Route as AuthenticatedMesasRouteImport } from './routes/_authenticated/mesas'
import { Route as AuthenticatedLucratividadeRouteImport } from './routes/_authenticated/lucratividade'
import { Route as AuthenticatedImpressaoRouteImport } from './routes/_authenticated/impressao'
import { Route as AuthenticatedImportarRouteImport } from './routes/_authenticated/importar'
import { Route as AuthenticatedGarconsRouteImport } from './routes/_authenticated/garcons'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedFichaTecnicaRouteImport } from './routes/_authenticated/ficha-tecnica'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedEntregasRouteImport } from './routes/_authenticated/entregas'
import { Route as AuthenticatedCopilotoRouteImport } from './routes/_authenticated/copiloto'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedCarrinhosRouteImport } from './routes/_authenticated/carrinhos'
import { Route as AuthenticatedCaixaRouteImport } from './routes/_authenticated/caixa'
import { Route as AuthenticatedBibliotecaRouteImport } from './routes/_authenticated/biblioteca'
import { Route as AuthenticatedAvaliacoesRouteImport } from './routes/_authenticated/avaliacoes'
import { Route as AuthenticatedAutomacoesRouteImport } from './routes/_authenticated/automacoes'
import { Route as AuthenticatedAiGrowthRouteImport } from './routes/_authenticated/ai-growth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedRastrearOrderIdRouteImport } from './routes/_authenticated/rastrear.$orderId'
import { Route as AuthenticatedAvaliarOrderIdRouteImport } from './routes/_authenticated/avaliar.$orderId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RecompensasRoute = RecompensasRouteImport.update({
  id: '/recompensas',
  path: '/recompensas',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const BaixarAppRoute = BaixarAppRouteImport.update({
  id: '/baixar-app',
  path: '/baixar-app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotChatRoute = ApiCopilotChatRouteImport.update({
  id: '/api/copilot-chat',
  path: '/api/copilot-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRushRoute = AuthenticatedRushRouteImport.update({
  id: '/rush',
  path: '/rush',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrevisaoRoute = AuthenticatedPrevisaoRouteImport.update({
  id: '/previsao',
  path: '/previsao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrecificacaoRoute =
  AuthenticatedPrecificacaoRouteImport.update({
    id: '/precificacao',
    path: '/precificacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPdvRoute = AuthenticatedPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModelosRoute = AuthenticatedModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMesasRoute = AuthenticatedMesasRouteImport.update({
  id: '/mesas',
  path: '/mesas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLucratividadeRoute =
  AuthenticatedLucratividadeRouteImport.update({
    id: '/lucratividade',
    path: '/lucratividade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImpressaoRoute = AuthenticatedImpressaoRouteImport.update({
  id: '/impressao',
  path: '/impressao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportarRoute = AuthenticatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGarconsRoute = AuthenticatedGarconsRouteImport.update({
  id: '/garcons',
  path: '/garcons',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFichaTecnicaRoute =
  AuthenticatedFichaTecnicaRouteImport.update({
    id: '/ficha-tecnica',
    path: '/ficha-tecnica',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntregasRoute = AuthenticatedEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCopilotoRoute = AuthenticatedCopilotoRouteImport.update({
  id: '/copiloto',
  path: '/copiloto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarrinhosRoute = AuthenticatedCarrinhosRouteImport.update({
  id: '/carrinhos',
  path: '/carrinhos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCaixaRoute = AuthenticatedCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBibliotecaRoute = AuthenticatedBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAvaliacoesRoute = AuthenticatedAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomacoesRoute = AuthenticatedAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiGrowthRoute = AuthenticatedAiGrowthRouteImport.update({
  id: '/ai-growth',
  path: '/ai-growth',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRastrearOrderIdRoute =
  AuthenticatedRastrearOrderIdRouteImport.update({
    id: '/rastrear/$orderId',
    path: '/rastrear/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAvaliarOrderIdRoute =
  AuthenticatedAvaliarOrderIdRouteImport.update({
    id: '/avaliar/$orderId',
    path: '/avaliar/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/baixar-app': typeof BaixarAppRoute
  '/carrinho': typeof CarrinhoRoute
  '/recompensas': typeof RecompensasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai-growth': typeof AuthenticatedAiGrowthRoute
  '/automacoes': typeof AuthenticatedAutomacoesRoute
  '/avaliacoes': typeof AuthenticatedAvaliacoesRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/carrinhos': typeof AuthenticatedCarrinhosRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/conta': typeof AuthenticatedContaRoute
  '/copiloto': typeof AuthenticatedCopilotoRoute
  '/entregas': typeof AuthenticatedEntregasRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/ficha-tecnica': typeof AuthenticatedFichaTecnicaRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/garcons': typeof AuthenticatedGarconsRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/impressao': typeof AuthenticatedImpressaoRoute
  '/lucratividade': typeof AuthenticatedLucratividadeRoute
  '/mesas': typeof AuthenticatedMesasRoute
  '/modelos': typeof AuthenticatedModelosRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pdv': typeof AuthenticatedPdvRoute
  '/precificacao': typeof AuthenticatedPrecificacaoRoute
  '/previsao': typeof AuthenticatedPrevisaoRoute
  '/rush': typeof AuthenticatedRushRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/copilot-chat': typeof ApiCopilotChatRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/avaliar/$orderId': typeof AuthenticatedAvaliarOrderIdRoute
  '/rastrear/$orderId': typeof AuthenticatedRastrearOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/baixar-app': typeof BaixarAppRoute
  '/carrinho': typeof CarrinhoRoute
  '/recompensas': typeof RecompensasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai-growth': typeof AuthenticatedAiGrowthRoute
  '/automacoes': typeof AuthenticatedAutomacoesRoute
  '/avaliacoes': typeof AuthenticatedAvaliacoesRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/carrinhos': typeof AuthenticatedCarrinhosRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/conta': typeof AuthenticatedContaRoute
  '/copiloto': typeof AuthenticatedCopilotoRoute
  '/entregas': typeof AuthenticatedEntregasRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/ficha-tecnica': typeof AuthenticatedFichaTecnicaRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/garcons': typeof AuthenticatedGarconsRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/impressao': typeof AuthenticatedImpressaoRoute
  '/lucratividade': typeof AuthenticatedLucratividadeRoute
  '/mesas': typeof AuthenticatedMesasRoute
  '/modelos': typeof AuthenticatedModelosRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pdv': typeof AuthenticatedPdvRoute
  '/precificacao': typeof AuthenticatedPrecificacaoRoute
  '/previsao': typeof AuthenticatedPrevisaoRoute
  '/rush': typeof AuthenticatedRushRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/copilot-chat': typeof ApiCopilotChatRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/avaliar/$orderId': typeof AuthenticatedAvaliarOrderIdRoute
  '/rastrear/$orderId': typeof AuthenticatedRastrearOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/baixar-app': typeof BaixarAppRoute
  '/carrinho': typeof CarrinhoRoute
  '/recompensas': typeof RecompensasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ai-growth': typeof AuthenticatedAiGrowthRoute
  '/_authenticated/automacoes': typeof AuthenticatedAutomacoesRoute
  '/_authenticated/avaliacoes': typeof AuthenticatedAvaliacoesRoute
  '/_authenticated/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/_authenticated/caixa': typeof AuthenticatedCaixaRoute
  '/_authenticated/carrinhos': typeof AuthenticatedCarrinhosRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/_authenticated/copiloto': typeof AuthenticatedCopilotoRoute
  '/_authenticated/entregas': typeof AuthenticatedEntregasRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/ficha-tecnica': typeof AuthenticatedFichaTecnicaRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/garcons': typeof AuthenticatedGarconsRoute
  '/_authenticated/importar': typeof AuthenticatedImportarRoute
  '/_authenticated/impressao': typeof AuthenticatedImpressaoRoute
  '/_authenticated/lucratividade': typeof AuthenticatedLucratividadeRoute
  '/_authenticated/mesas': typeof AuthenticatedMesasRoute
  '/_authenticated/modelos': typeof AuthenticatedModelosRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/pdv': typeof AuthenticatedPdvRoute
  '/_authenticated/precificacao': typeof AuthenticatedPrecificacaoRoute
  '/_authenticated/previsao': typeof AuthenticatedPrevisaoRoute
  '/_authenticated/rush': typeof AuthenticatedRushRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/copilot-chat': typeof ApiCopilotChatRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/_authenticated/avaliar/$orderId': typeof AuthenticatedAvaliarOrderIdRoute
  '/_authenticated/rastrear/$orderId': typeof AuthenticatedRastrearOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/baixar-app'
    | '/carrinho'
    | '/recompensas'
    | '/sitemap.xml'
    | '/admin'
    | '/ai-growth'
    | '/automacoes'
    | '/avaliacoes'
    | '/biblioteca'
    | '/caixa'
    | '/carrinhos'
    | '/clientes'
    | '/conta'
    | '/copiloto'
    | '/entregas'
    | '/estoque'
    | '/ficha-tecnica'
    | '/financeiro'
    | '/garcons'
    | '/importar'
    | '/impressao'
    | '/lucratividade'
    | '/mesas'
    | '/modelos'
    | '/notificacoes'
    | '/pdv'
    | '/precificacao'
    | '/previsao'
    | '/rush'
    | '/usuarios'
    | '/api/copilot-chat'
    | '/produto/$id'
    | '/avaliar/$orderId'
    | '/rastrear/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/baixar-app'
    | '/carrinho'
    | '/recompensas'
    | '/sitemap.xml'
    | '/admin'
    | '/ai-growth'
    | '/automacoes'
    | '/avaliacoes'
    | '/biblioteca'
    | '/caixa'
    | '/carrinhos'
    | '/clientes'
    | '/conta'
    | '/copiloto'
    | '/entregas'
    | '/estoque'
    | '/ficha-tecnica'
    | '/financeiro'
    | '/garcons'
    | '/importar'
    | '/impressao'
    | '/lucratividade'
    | '/mesas'
    | '/modelos'
    | '/notificacoes'
    | '/pdv'
    | '/precificacao'
    | '/previsao'
    | '/rush'
    | '/usuarios'
    | '/api/copilot-chat'
    | '/produto/$id'
    | '/avaliar/$orderId'
    | '/rastrear/$orderId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/baixar-app'
    | '/carrinho'
    | '/recompensas'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/ai-growth'
    | '/_authenticated/automacoes'
    | '/_authenticated/avaliacoes'
    | '/_authenticated/biblioteca'
    | '/_authenticated/caixa'
    | '/_authenticated/carrinhos'
    | '/_authenticated/clientes'
    | '/_authenticated/conta'
    | '/_authenticated/copiloto'
    | '/_authenticated/entregas'
    | '/_authenticated/estoque'
    | '/_authenticated/ficha-tecnica'
    | '/_authenticated/financeiro'
    | '/_authenticated/garcons'
    | '/_authenticated/importar'
    | '/_authenticated/impressao'
    | '/_authenticated/lucratividade'
    | '/_authenticated/mesas'
    | '/_authenticated/modelos'
    | '/_authenticated/notificacoes'
    | '/_authenticated/pdv'
    | '/_authenticated/precificacao'
    | '/_authenticated/previsao'
    | '/_authenticated/rush'
    | '/_authenticated/usuarios'
    | '/api/copilot-chat'
    | '/produto/$id'
    | '/_authenticated/avaliar/$orderId'
    | '/_authenticated/rastrear/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BaixarAppRoute: typeof BaixarAppRoute
  CarrinhoRoute: typeof CarrinhoRoute
  RecompensasRoute: typeof RecompensasRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiCopilotChatRoute: typeof ApiCopilotChatRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recompensas': {
      id: '/recompensas'
      path: '/recompensas'
      fullPath: '/recompensas'
      preLoaderRoute: typeof RecompensasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baixar-app': {
      id: '/baixar-app'
      path: '/baixar-app'
      fullPath: '/baixar-app'
      preLoaderRoute: typeof BaixarAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilot-chat': {
      id: '/api/copilot-chat'
      path: '/api/copilot-chat'
      fullPath: '/api/copilot-chat'
      preLoaderRoute: typeof ApiCopilotChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rush': {
      id: '/_authenticated/rush'
      path: '/rush'
      fullPath: '/rush'
      preLoaderRoute: typeof AuthenticatedRushRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/previsao': {
      id: '/_authenticated/previsao'
      path: '/previsao'
      fullPath: '/previsao'
      preLoaderRoute: typeof AuthenticatedPrevisaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/precificacao': {
      id: '/_authenticated/precificacao'
      path: '/precificacao'
      fullPath: '/precificacao'
      preLoaderRoute: typeof AuthenticatedPrecificacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pdv': {
      id: '/_authenticated/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof AuthenticatedPdvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modelos': {
      id: '/_authenticated/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof AuthenticatedModelosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mesas': {
      id: '/_authenticated/mesas'
      path: '/mesas'
      fullPath: '/mesas'
      preLoaderRoute: typeof AuthenticatedMesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lucratividade': {
      id: '/_authenticated/lucratividade'
      path: '/lucratividade'
      fullPath: '/lucratividade'
      preLoaderRoute: typeof AuthenticatedLucratividadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impressao': {
      id: '/_authenticated/impressao'
      path: '/impressao'
      fullPath: '/impressao'
      preLoaderRoute: typeof AuthenticatedImpressaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importar': {
      id: '/_authenticated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AuthenticatedImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/garcons': {
      id: '/_authenticated/garcons'
      path: '/garcons'
      fullPath: '/garcons'
      preLoaderRoute: typeof AuthenticatedGarconsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ficha-tecnica': {
      id: '/_authenticated/ficha-tecnica'
      path: '/ficha-tecnica'
      fullPath: '/ficha-tecnica'
      preLoaderRoute: typeof AuthenticatedFichaTecnicaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entregas': {
      id: '/_authenticated/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof AuthenticatedEntregasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copiloto': {
      id: '/_authenticated/copiloto'
      path: '/copiloto'
      fullPath: '/copiloto'
      preLoaderRoute: typeof AuthenticatedCopilotoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carrinhos': {
      id: '/_authenticated/carrinhos'
      path: '/carrinhos'
      fullPath: '/carrinhos'
      preLoaderRoute: typeof AuthenticatedCarrinhosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caixa': {
      id: '/_authenticated/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof AuthenticatedCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblioteca': {
      id: '/_authenticated/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AuthenticatedBibliotecaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avaliacoes': {
      id: '/_authenticated/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/avaliacoes'
      preLoaderRoute: typeof AuthenticatedAvaliacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automacoes': {
      id: '/_authenticated/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AuthenticatedAutomacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-growth': {
      id: '/_authenticated/ai-growth'
      path: '/ai-growth'
      fullPath: '/ai-growth'
      preLoaderRoute: typeof AuthenticatedAiGrowthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rastrear/$orderId': {
      id: '/_authenticated/rastrear/$orderId'
      path: '/rastrear/$orderId'
      fullPath: '/rastrear/$orderId'
      preLoaderRoute: typeof AuthenticatedRastrearOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avaliar/$orderId': {
      id: '/_authenticated/avaliar/$orderId'
      path: '/avaliar/$orderId'
      fullPath: '/avaliar/$orderId'
      preLoaderRoute: typeof AuthenticatedAvaliarOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAiGrowthRoute: typeof AuthenticatedAiGrowthRoute
  AuthenticatedAutomacoesRoute: typeof AuthenticatedAutomacoesRoute
  AuthenticatedAvaliacoesRoute: typeof AuthenticatedAvaliacoesRoute
  AuthenticatedBibliotecaRoute: typeof AuthenticatedBibliotecaRoute
  AuthenticatedCaixaRoute: typeof AuthenticatedCaixaRoute
  AuthenticatedCarrinhosRoute: typeof AuthenticatedCarrinhosRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedCopilotoRoute: typeof AuthenticatedCopilotoRoute
  AuthenticatedEntregasRoute: typeof AuthenticatedEntregasRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedFichaTecnicaRoute: typeof AuthenticatedFichaTecnicaRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedGarconsRoute: typeof AuthenticatedGarconsRoute
  AuthenticatedImportarRoute: typeof AuthenticatedImportarRoute
  AuthenticatedImpressaoRoute: typeof AuthenticatedImpressaoRoute
  AuthenticatedLucratividadeRoute: typeof AuthenticatedLucratividadeRoute
  AuthenticatedMesasRoute: typeof AuthenticatedMesasRoute
  AuthenticatedModelosRoute: typeof AuthenticatedModelosRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPdvRoute: typeof AuthenticatedPdvRoute
  AuthenticatedPrecificacaoRoute: typeof AuthenticatedPrecificacaoRoute
  AuthenticatedPrevisaoRoute: typeof AuthenticatedPrevisaoRoute
  AuthenticatedRushRoute: typeof AuthenticatedRushRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedAvaliarOrderIdRoute: typeof AuthenticatedAvaliarOrderIdRoute
  AuthenticatedRastrearOrderIdRoute: typeof AuthenticatedRastrearOrderIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAiGrowthRoute: AuthenticatedAiGrowthRoute,
  AuthenticatedAutomacoesRoute: AuthenticatedAutomacoesRoute,
  AuthenticatedAvaliacoesRoute: AuthenticatedAvaliacoesRoute,
  AuthenticatedBibliotecaRoute: AuthenticatedBibliotecaRoute,
  AuthenticatedCaixaRoute: AuthenticatedCaixaRoute,
  AuthenticatedCarrinhosRoute: AuthenticatedCarrinhosRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedCopilotoRoute: AuthenticatedCopilotoRoute,
  AuthenticatedEntregasRoute: AuthenticatedEntregasRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedFichaTecnicaRoute: AuthenticatedFichaTecnicaRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedGarconsRoute: AuthenticatedGarconsRoute,
  AuthenticatedImportarRoute: AuthenticatedImportarRoute,
  AuthenticatedImpressaoRoute: AuthenticatedImpressaoRoute,
  AuthenticatedLucratividadeRoute: AuthenticatedLucratividadeRoute,
  AuthenticatedMesasRoute: AuthenticatedMesasRoute,
  AuthenticatedModelosRoute: AuthenticatedModelosRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPdvRoute: AuthenticatedPdvRoute,
  AuthenticatedPrecificacaoRoute: AuthenticatedPrecificacaoRoute,
  AuthenticatedPrevisaoRoute: AuthenticatedPrevisaoRoute,
  AuthenticatedRushRoute: AuthenticatedRushRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedAvaliarOrderIdRoute: AuthenticatedAvaliarOrderIdRoute,
  AuthenticatedRastrearOrderIdRoute: AuthenticatedRastrearOrderIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BaixarAppRoute: BaixarAppRoute,
  CarrinhoRoute: CarrinhoRoute,
  RecompensasRoute: RecompensasRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiCopilotChatRoute: ApiCopilotChatRoute,
  ProdutoIdRoute: ProdutoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
