/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecompensasRouteImport } from './routes/recompensas'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as BaixarAppRouteImport } from './routes/baixar-app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedCarrinhosRouteImport } from './routes/_authenticated/carrinhos'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const RecompensasRoute = RecompensasRouteImport.update({
  id: '/recompensas',
  path: '/recompensas',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const BaixarAppRoute = BaixarAppRouteImport.update({
  id: '/baixar-app',
  path: '/baixar-app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarrinhosRoute = AuthenticatedCarrinhosRouteImport.update({
  id: '/carrinhos',
  path: '/carrinhos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/baixar-app': typeof BaixarAppRoute
  '/carrinho': typeof CarrinhoRoute
  '/recompensas': typeof RecompensasRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/carrinhos': typeof AuthenticatedCarrinhosRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/conta': typeof AuthenticatedContaRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/baixar-app': typeof BaixarAppRoute
  '/carrinho': typeof CarrinhoRoute
  '/recompensas': typeof RecompensasRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/carrinhos': typeof AuthenticatedCarrinhosRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/conta': typeof AuthenticatedContaRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/baixar-app': typeof BaixarAppRoute
  '/carrinho': typeof CarrinhoRoute
  '/recompensas': typeof RecompensasRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/carrinhos': typeof AuthenticatedCarrinhosRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/baixar-app'
    | '/carrinho'
    | '/recompensas'
    | '/admin'
    | '/carrinhos'
    | '/clientes'
    | '/conta'
    | '/financeiro'
    | '/notificacoes'
    | '/pedidos'
    | '/produto/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/baixar-app'
    | '/carrinho'
    | '/recompensas'
    | '/admin'
    | '/carrinhos'
    | '/clientes'
    | '/conta'
    | '/financeiro'
    | '/notificacoes'
    | '/pedidos'
    | '/produto/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/baixar-app'
    | '/carrinho'
    | '/recompensas'
    | '/_authenticated/admin'
    | '/_authenticated/carrinhos'
    | '/_authenticated/clientes'
    | '/_authenticated/conta'
    | '/_authenticated/financeiro'
    | '/_authenticated/notificacoes'
    | '/_authenticated/pedidos'
    | '/produto/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BaixarAppRoute: typeof BaixarAppRoute
  CarrinhoRoute: typeof CarrinhoRoute
  RecompensasRoute: typeof RecompensasRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recompensas': {
      id: '/recompensas'
      path: '/recompensas'
      fullPath: '/recompensas'
      preLoaderRoute: typeof RecompensasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baixar-app': {
      id: '/baixar-app'
      path: '/baixar-app'
      fullPath: '/baixar-app'
      preLoaderRoute: typeof BaixarAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carrinhos': {
      id: '/_authenticated/carrinhos'
      path: '/carrinhos'
      fullPath: '/carrinhos'
      preLoaderRoute: typeof AuthenticatedCarrinhosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCarrinhosRoute: typeof AuthenticatedCarrinhosRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCarrinhosRoute: AuthenticatedCarrinhosRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BaixarAppRoute: BaixarAppRoute,
  CarrinhoRoute: CarrinhoRoute,
  RecompensasRoute: RecompensasRoute,
  ProdutoIdRoute: ProdutoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
