DROP VIEW IF EXISTS public.site_settings_public;

CREATE VIEW public.site_settings_public
WITH (security_invoker = true) AS
SELECT
  id,
  name,
  tagline,
  city,
  address,
  hours,
  whatsapp,
  whatsapp_display,
  maps_url,
  map_embed,
  delivery_fee,
  logo_url,
  texture_url,
  updated_at,
  instagram,
  facebook,
  tiktok,
  announcement_text,
  announcement_active,
  payment_methods,
  free_delivery_threshold,
  min_order,
  accepts_delivery,
  accepts_pickup,
  open_override,
  hours_json,
  news_active,
  news_title,
  news_product_ids,
  news_subtitle,
  news_ticker,
  global_extras,
  bg_color,
  accent_color,
  texture_opacity,
  texture_size,
  card_radius,
  card_border,
  card_glow,
  title_font,
  hero_images,
  popup_active,
  popup_title,
  popup_body,
  popup_image_url,
  popup_link,
  popup_cta,
  popup_image_pos_x,
  popup_image_pos_y,
  popup_image_scale,
  popup_frequency,
  urgency_active,
  urgency_text,
  urgency_ends_at,
  urgency_coupon_code,
  store_lat,
  store_lng,
  delivery_zone_json
FROM public.site_settings
WHERE id = 1;

GRANT SELECT ON public.site_settings_public TO anon;
GRANT SELECT ON public.site_settings_public TO authenticated;
GRANT SELECT ON public.site_settings_public TO service_role;