REVOKE EXECUTE ON FUNCTION public.validate_loyalty_coupon(text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.redeem_loyalty_coupon(text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.validate_promo_coupon(text, numeric) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.redeem_promo_coupon(text, numeric, uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM anon, public;
GRANT EXECUTE ON FUNCTION public.validate_loyalty_coupon(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.redeem_loyalty_coupon(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.validate_promo_coupon(text, numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.redeem_promo_coupon(text, numeric, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated;